Apps/alunos/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    ]

apps/alunos/urls.py
from django.urls import path
from . import views


app_name = 'apps.alunos'

urlpatterns = [
    path('inserir_aluno/', views.inserir_aluno, name='inserir_aluno'),
    path('listar_alunos/', views.listar_alunos, name='listar_alunos'),
    path('editar_aluno/<int:id>/', views.editar_aluno, name='editar_aluno'),
    path('excluir_aluno/<int:id>/', views.excluir_aluno, name='excluir_aluno'),
]

biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.core.views import index


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('alunos/', include('apps.alunos.urls', namespace='alunos')),
    path('livros/', include('apps.livros.urls', namespace='livros')),
    path('emprestimos/', include('apps.emprestimos.urls', namespace='emprestimos')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/alunos/models.py
from django.db import models
from datetime import date

class Aluno(models.Model):
    nome = models.CharField(max_length=100, blank=False, null=False)
    matricula = models.CharField(max_length=20, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    telefone = models.CharField(max_length=20, blank=False, null=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    # Data de última modificação automática
    ultima_modificacao = models.DateTimeField(auto_now=True)
    # Data de um evento específico (padrão pode ser alterado)
    data_evento = models.DateField(default=date.today)


    def __str__(self):
        return self.nome

apps/alunos/forms.py
from django import forms
from django.forms import ModelForm, DateInput

from .models import Aluno

class AlunoForm(forms.ModelForm):

    class Meta:
        model = Aluno
        exclude = ['data_criacao', 'ultima_modificacao', 'data_evento']
        fields = '__all__'

Apps/alunos/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    return HttpResponse("Cadastro de Alunos!")

apps/alunos/views.py
from django.contrib import messages

from .forms import AlunoForm
from django.shortcuts import render, redirect, get_object_or_404

from .models import Aluno
from django.db.models.functions import Lower

def inserir_aluno(request):
    template_name = 'alunos/form_aluno.html'
    if request.method == 'POST':
        form = AlunoForm(request.POST or None, request.FILES)
        if form.is_valid():
            form.save()
            # messages.success(request, 'O Aluno salvo com sucesso.')
            return redirect('alunos:listar_alunos')
    form = AlunoForm()
    context = {'form': form}
    return render(request, template_name, context)

def listar_alunos(request):
    template_name = 'alunos/listar_alunos.html'
    alunos = Aluno.objects.all()
    context = {'alunos': alunos}
    return render(request, template_name, context)

def editar_aluno(request, id):
    template_name = 'alunos/atualizar_aluno.html'
    aluno = get_object_or_404(Aluno, id=id)
    form = AlunoForm(request.POST or None, request.FILES or None, instance=aluno)
    context = {'form': form}
    if form.is_valid():
        form.save()
        messages.success(request, 'Os dados foram atualizados com sucesso.')
        return redirect('alunos:listar_alunos')
    return render(request, template_name, context)

def excluir_aluno(request, id):
    template_name = 'alunos/excluir_aluno.html'
    aluno = Aluno.objects.get(id=id)
    context = {'aluno': aluno}
    if request.method == "POST":
        aluno.delete()
        messages.error(request, 'O Aluno foi excluído com sucesso!')
        return redirect('alunos:listar_alunos')
    return render(request, template_name, context)

def listar_alunos(request):
    template_name = 'alunos/listar_alunos.html'

    ordem = request.GET.get('ordem', 'id_asc')  # padrão

    if ordem == 'nome_asc':
        alunos = Aluno.objects.all().order_by(Lower('nome'))
    elif ordem == 'nome_desc':
        alunos = Aluno.objects.all().order_by(Lower('nome').desc())
    elif ordem == 'id_asc':
        alunos = Aluno.objects.all().order_by('id')
    elif ordem == 'id_desc':
        alunos = Aluno.objects.all().order_by('-id')
    elif ordem == 'matricula_asc':
        alunos = Aluno.objects.all().order_by('matricula')
    elif ordem == 'matricula_desc':
        alunos = Aluno.objects.all().order_by('-matricula')
    else:
        alunos = Aluno.objects.all().order_by('id')

    context = {
        'alunos': alunos,
        'ordem': ordem,
    }
    return render(request, template_name, context)

apps/alunos/templates/alunos/atualizar_aluno.html
{% load crispy_forms_tags %}

{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="row">
        <div class="col-12"></div>
    </div>
    <div class="card">
        <div class="card-header">
            <h2><i class="fa fa-users"></i> Atualização de Alunos</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-8">
                                {{ form.nome.errors }}
                                <label><strong>Nome: </strong></label>
                                {{ form.nome|add_class:"form-control" }}
                            </div>
                            <div class="col-md-4">
                                {{ form.matricula.errors }}
                                <label><strong>Matrícula: </strong></label>
                                {{ form.matricula|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-8">
                                {{ form.email.errors }}
                                <label><strong>Email:</strong></label>
                                {{ form.email|add_class:'form-control' }}
                            </div>
                            <div class="col-md-4 mb-0">
                                {{ form.telefone.errors }}
                                <label><strong>Telefone:</strong></label>
                                {{ form.telefone|add_class:'form-control'  }}
                            </div>
                            <div class="col-md-3">
                                {{ form.data_evento.erros }}
                                <label><strong>Data da Atualização:</strong></label>
                                {{ form.data_evento|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-12">
                               <button type="submit" class="btn btn-success">Atualizar</button>
                               <a href="{{request.META.HTTP_REFERER}}"><button type="button" class="btn btn-primary">Voltar</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</body>
</html>

apps/alunos/templates/alunos/excluir_aluno.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
<div class="card">
    <div class="card-header">
        Tem certeza que deseja remover o aluno abaixo?
    </div>
    <div class="card-body">
        <h5 class="card-title">Id: {{aluno.id}}</h5>
        <h5 class="card-title">Aluno: {{aluno.nome}}</h5>
        <h5 class="card-title">Matrícula: {{aluno.matricula}}</h5>
        <h5 class="card-title">Email: {{aluno.email}}</h5>
        <h5 class="card-title">Telefone: {{aluno.telefone}}</h5>
        <h5 class="card-title">Data de Criação: {{aluno.data_criacao}}</h5>

        <form method="post">
             {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Voltar</a>
        </form>
    </div>
</div>
</body>
</html>

apps/alunos/templates/alunos/form_aluno.html
{% load crispy_forms_tags %}

{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="row">
        <div class="col-12"></div>
    </div>
    <div class="card">
        <div class="card-header">
            <h2><i class="fa fa-users"></i> Cadastro de Alunos</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="row">
                            <div class="col-md-8">
                                {{ form.nome.errors }}
                                <label><strong>Nome: </strong></label>
                                {{ form.nome|add_class:"form-control" }}
                            </div>
                            <div class="col-md-4">
                                {{ form.matricula.errors }}
                                <label><strong>Matrícula: </strong></label>
                                {{ form.matricula|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="row">
                            <div class="col-md-8">
                                {{ form.email.errors }}
                                <label><strong>Email:</strong></label>
                                {{ form.email|add_class:'form-control' }}
                            </div>
                            <div class="col-md-4 mb-0">
                                {{ form.telefone.errors }}
                                <label><strong>Telefone:</strong></label>
                                {{ form.telefone|add_class:'form-control'  }}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-12">
                               <button type="submit" class="btn btn-success">Salvar</button>
                               <a href="{{request.META.HTTP_REFERER}}"><button type="button" class="btn btn-primary">Voltar</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</body>
</html>

apps/alunos/templates/alunos/listar_alunos.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-12">
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h2><i class="fa fa-list">{% block title %}Listagem de alunos{% endblock %}</i></h2>
        </div>
        <div class="card-body">

            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

            <div class="mb-3">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="ordenarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            Ordenar
        </button>
        <ul class="dropdown-menu" aria-labelledby="ordenarDropdown">
            <li><a class="dropdown-item" href="?ordem=nome_asc">Nome A → Z</a></li>
            <li><a class="dropdown-item" href="?ordem=nome_desc">Nome Z → A</a></li>
            <li><a class="dropdown-item" href="?ordem=id_asc">ID Crescente</a></li>
            <li><a class="dropdown-item" href="?ordem=id_desc">ID Decrescente</a></li>
            <li><a class="dropdown-item" href="?ordem=matricula_asc">Matrícula Crescente</a></li>
            <li><a class="dropdown-item" href="?ordem=matricula_desc">Matrícula Decrescente</a></li>
        </ul>
    </div>

            </div>


            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
            <div class="table-responsive">
                <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Matrícula</th>
                            <th>E-mail</th>
                            <th>Telefone</th>
                            <th>Data Cadastro</th>
                            <th>Data Atualização</th>
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for a in alunos %}
                        <tr>
                            <td>{{ a.id }}</td>
                            <td><a href="#">{{ a.nome.upper }}</a></td>
                            <td>{{ a.matricula }}</td>
                            <td>{{ a.email }}</td>
                            <td>{{ a.telefone }}</td>
                            <td>{{ a.data_criacao  | date:'d/m/Y'}}</td>
                            <td>{{ a.ultima_modificacao  | date:'d/m/Y'}}</td>
                            <td>
                                <a href="#">
                                    <i class="fa fa-search" aria-hidden="true" style="color: blue;"></i>
                                </a>
                                <a href="{% url 'alunos:editar_aluno' a.id%}">
                                    <i class="fa fa-pencil-square" aria-hidden="true" style="color: #6B8E23;"></i>
                                </a>
                                <a href="{% url 'alunos:excluir_aluno' a.id%}">
                                    <i class="fa fa-trash" aria-hidden="true" style="color: red;"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-12 card mb-3">
        <div class="card-header">
            <a href="{% url 'alunos:inserir_aluno' %}"><button class="btn btn-success">Cadastrar</button></a>
            <a href="{% url 'index' %}"><button class="btn btn-primary">Voltar</button></a>
        </div>
    </div>
{% endblock %}